### ISSUE TITLE
Duplicate xdebug keys

### ISSUE THREAD

**Issue by bmartinez287** [mikemadison13/blt-lando#21]
```
config:
  webroot: docroot
  xdebug: false
  php: '7.4'
services:
  appserver:
    xdebug: false
    build_as_root:

```

Does it make sense to have the xdebug key in two places? If so why?
